[server]
enableXsrfProtection = false
enableCORS = false

[runner]
fastReruns = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#f63366"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e2130"
textColor = "#ffffff"
